services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "library" ]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    environment:
      DB_DSN: postgres://library:library@db:5432/library?sslmode=disable
      HTTP_ADDR: :8080
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static

volumes:
  dbdata: